security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="XXXXXXXXXX" password="XXXXXXXXXX/Kmrs9g3A";
ssl.truststore.location=/etc/kafka/tls/truststore.jks
ssl.truststore.password=clienttrustpass
ssl.endpoint.identification.algorithm=