#!/bin/bash

# Script to verify and update Cloud API key permissions

echo "=============================================="
echo "Confluent Cloud API Key Permission Checker"
echo "=============================================="
echo ""
echo "Your API Key: PPBQ6IBKOFRNECEG"
echo "Current Permission: Cloud resource management"
echo ""
echo "=============================================="
echo "Required Permission for ACL Creation:"
echo "=============================================="
echo ""
echo "Your Cloud API key needs one of these roles:"
echo "  ✓ OrganizationAdmin"
echo "  ✓ EnvironmentAdmin"
echo ""
echo "=============================================="
echo "How to Grant Permissions:"
echo "=============================================="
echo ""
echo "METHOD 1: Confluent Cloud UI (Recommended)"
echo "-------------------------------------------"
echo ""
echo "1. Go to: https://confluent.cloud/settings/api-keys"
echo ""
echo "2. Find API Key: PPBQ6IBKOFRNECEG"
echo ""
echo "3. Click on the key and look for 'Role bindings' section"
echo ""
echo "4. Click 'Add role binding'"
echo ""
echo "5. Select:"
echo "   - Role: OrganizationAdmin (or EnvironmentAdmin)"
echo "   - Scope: Your organization (or specific environment)"
echo ""
echo "6. Click 'Save'"
echo ""
echo "METHOD 2: Using Confluent CLI"
echo "-------------------------------------------"
echo ""
echo "# Install Confluent CLI if needed"
echo "# https://docs.confluent.io/confluent-cli/current/install.html"
echo ""
echo "# Login"
echo "confluent login"
echo ""
echo "# List current role bindings for your user"
echo "confluent iam rbac role-binding list"
echo ""
echo "# Grant OrganizationAdmin to your API key's service account"
echo "# First, find the service account ID for your API key"
echo "confluent api-key list --resource cloud"
echo ""
echo "# Then grant the role (replace SA-ID with actual service account ID)"
echo "confluent iam rbac role-binding create \\"
echo "  --principal User:<SA-ID> \\"
echo "  --role OrganizationAdmin"
echo ""
echo "=============================================="
echo "After Granting Permissions:"
echo "=============================================="
echo ""
echo "cd confluent-terraform"
echo "terraform apply"
echo ""
echo "=============================================="
echo "Alternative: Create New Admin API Key"
echo "=============================================="
echo ""
echo "If you prefer to create a new API key with admin permissions:"
echo ""
echo "1. Go to: https://confluent.cloud/settings/api-keys"
echo "2. Click '+ Add key'"
echo "3. Select 'Cloud resource management'"
echo "4. After creation, grant it OrganizationAdmin role"
echo "5. Update .env file with new credentials"
echo "6. Run: terraform apply"
echo ""
