apiVersion: v1
kind: Pod
metadata:
  name: kafka-tools
  namespace: confluent
spec:
  restartPolicy: Never
  hostAliases:
    - ip: "52.38.125.114" #Change after running NSLOOKUP to your ALB
      hostnames:
        - "kafka.cpc.yesh.com"
    - ip: "52.89.255.46" #Change after running NSLOOKUP to your ALB
      hostnames:
        - "kafka.cpc.yesh.com"
  securityContext:
    # Ensures the container user can read files from the Secret volume
    fsGroup: 1000
  containers:
    - name: tools
      image: confluentinc/cp-kafka:8.1.0
      command: ["bash", "-lc"]
      args:
        - sleep infinity
      volumeMounts:
        - name: gateway-truststore
          mountPath: /etc/kafka/tls
          readOnly: true
        - name: client-primary
          mountPath: /etc/kafka/client-primary
          readOnly: true
        - name: client-dr
          mountPath: /etc/kafka/client-dr
          readOnly: true
  volumes:
    - name: gateway-truststore
      secret:
        secretName: gateway-truststore
        defaultMode: 0400
    - name: client-primary
      secret:
        secretName: client-primary
        defaultMode: 0400
    - name: client-dr
      secret:
        secretName: client-dr
        defaultMode: 0400
